#!/bin/sh
# save the file as <git_directory>/.git/hooks/pre-commit

echo "Running Maven Spotless Check to Check Your Code Style!"
# retrieving current working directory
CWD=`pwd`
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# go to main project dir
cd $MAIN_DIR/../../

mvn spotless:check
if [ $? -ne 0 ]; then
  "Error while testing the code"
  # go back to current working dir
  cd $CWD
  exit 1
fi

# go back to current working dir
cd $CWD
