server.port: 8083
application.name: bunny-ddd-sample

spring.jpa.hibernate.ddl-auto: update

bunny.ddd.enabled: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

knife4j:
  enable: true
  setting:
    enableSwaggerModels: true
    swaggerModelName: 领域模型
  documents:
    -
      group: 1.2.x
      name: 测试自定义标题分组
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*