#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url: jdbc:postgresql://localhost:5432/bunny
#spring.datasource.username: postgres
#spring.datasource.password: example

spring.datasource.url: jdbc:mariadb://192.168.50.49:3307/ent
spring.datasource.driverClassName: org.mariadb.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: Ztou135@$^
spring.jpa.database-platform: org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto: create