spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url: jdbc:postgresql://192.168.50.250:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: example

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.jpa.hibernate.ddl-auto: update


